### ISSUE TITLE
 curl: not found & tinyramfs: not found [still problem exists!]

### ISSUE THREAD

**Issue by spacedream** [eudaldgr/kiss-live#5] opened 2020-11-04 17:55 UTC
[xx@localhost kiss-live]$ sudo ./kiss-live -c "/home/xx/kiss-live/keess-cache" -d
...
...
-> linux-headers Verifying installation
-> linux-headers Installed successfully
-> util-linux Downloading sources
-> util-linux Downloading https://cdn.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.xz
/usr/bin/kiss: line 210: curl: not found
ERROR util-linux Failed to download https://cdn.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.xz
-> util-linux not installed
/bin/sh: tinyramfs: not found
!! Failed create initramfs
rm: cannot remove '/home/xx/kiss-live/rootfs/root/.cache/kiss/sources': Device or resource busy
[xx@localhost kiss-live]$
[xx@localhost kiss-live]$ whereis curl
curl: /usr/bin/curl /usr/include/curl /usr/share/man/man1/curl.1.bz2
[xx@localhost kiss-live]$ whereis tinyramfs
tinyramfs: /usr/bin/tinyramfs /etc/tinyramfs /usr/share/tinyramfs /usr/share/man/man8/tinyramfs.8

Im using linux gentoo on amd64, trying to make your script do work but so far its keep failing. Also im on slow limited connection, every time its re-downloading all sources again and again... its really painful, can you add please to your script the check for all files and skip downloading them (maybe for "-c" option only) if its already pre-downloaded (in external) folder? maybe best with checksum? for make sure no corrupted files. thank you!

**Comment by eudaldgr** [comment] 2020-11-04 19:04
Well, first of all, `curl` is not found inside the chroot, so `util-linux` can't install, so `tinyramfs` can't install also.
All occurs inside the chroot, you don't need to install them on your system, but that's weird because `curl` was not removed by the script.

The second thing is that there is an option to not need to re-download all, the `-c <dir>` flag. You are using it, so i don't see why it would re-download all again.

Have you made a git pull lately? Because at the moment you made the issue, there is an error i didn't update a fix, so you have an old version of the script, if it is not impossible that you have reached so far in the execution.

I fixed now [`03fb775`](https://github.com/eudaldgr/kiss-live/commit/03fb7759e86e43450f233f93cfc4635e3b36c6af). So please, update the repo before post an issue.

**Comment by eudaldgr** [comment] 2020-11-04 19:09
The error I mentioned has nothing to do with yours, so I know you have the script out of date.

**Comment by spacedream** [comment] 2020-11-10 21:57
well... i tryed just yesterday again. i removed my old folder with kiss-live and download its again, fresh one.
as result - same story, at the end:
...
-> linux-headers Checking repository files
-> util-linux Checking repository files
-> tinyramfs Checking repository files
-> Checking for pre-built dependencies 
-> linux-headers Found pre-built binary, installing
-> linux-headers Checking for package conflicts
-> linux-headers Installing package
-> linux-headers Verifying installation
-> linux-headers Installed successfully
-> util-linux Downloading sources
-> util-linux Downloading https://cdn.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.xz
/usr/bin/kiss: line 230: curl: not found
ERROR util-linux Failed to download https://cdn.kernel.org/pub/linux/utils/util-linux/v2.36/util-linux-2.36.tar.xz
/bin/sh: tinyramfs: not found
!! Failed create initramfs
[xx@localhost kiss-live]$ 

ps: i'm not "complaining" or crying, but trying to improve and make your baby better. off course if its exactly your intention too. otherwise i'll give up and walk away, just let me know ;)

**Comment by spacedream** [comment] 2020-11-10 22:06
i looked at log file and its not exists even (why?)
/root/.cache/kiss/logs//post-install-2020-11-10-21:38-2994
No such file but directory logs exists and empty
anyway, i think will be better if its will writing log in to local same directory were script run from, but not in /root (what real reason for?). thank you again for your nice script, i hope we can make it better some day :)  and sorry for my poor english, its not my native language.

**Comment by spacedream** [comment] 2020-11-10 22:16
ps: this time i did run your script without any options:
$> sudo ./kiss-live
its was running on my i5 laptop for about long 9 hours. i'm on slow and expensive wireless connection (ala 2G), last time when i did re-run your script its started downloading bold files from internet again. but why? if its was downloaded already somethere. its what exactly i was meant in my previous messages above. thank you again for your help. hope we can resolve this somehow. i like k1ss and its ideas, don't want to give up too yearly on your creation. thank you again.

**Comment by spacedream** [comment] 2020-11-10 23:15
Okey, i trying to debug this problems again.
i start now script like this:
$> time sudo nice -n 18 ./kiss-live -c /home/xx/ut/tmp/k1ss/kiss-live/k1ss_cache/ -p curl -d
its periodicaly saying its wroting log in to
/root/.cache/kiss/logs//post-install-2020-11-11-04:59-14426
so, i opened another terminal and did look at this folder and its empty. no log file there. why? and how to debug/fix this?
i hope on your help, friend. thank you!

**Comment by spacedream** [comment] 2020-11-11 04:41
Okey, i think you not reading here anymore, so i will open new ticket then.

**Comment by eudaldgr** [comment] 2020-11-11 19:42
Thanks for the reports, i understand your frustration with this issue.

Logs inside `~/.cache/kiss/logs` are logs from the package manager `kiss`, created when it installs some package, i didn't decide where they are stored.

The .txt file from #6 shows only the part from `tinyramfs` this is another project, but are you tried to run `kiss-live` with another linux kernel (5.8.16-pentoo) instead of the one i provide?
And then you think you list the file that `tinyramfs` didn't find in the same directory, but it's another dir.
`tinyramfs` runs inside the chroot, so they try to find the things inside the chroot, the host libraries doesn't matter.

I can reproduce that `curl` is missing after the remove orphans, so i will send a fix for this.

**Closed as completed** 2020-11-11 19:43 UTC
Labels: invalid

**Comment by spacedream** [comment] 2020-11-11 21:27
> but are you tried to run kiss-live with another linux kernel (5.8.16-pentoo) **instead of the one i provide**?

i not sure what you talking about. i running gentoo but with pentoo kernel (only), as i can select any kernel on this system. basically its a same kernel as in any another system. its a problem? i guess (and hope) not. 
anyway, i just run your script on system only i have. and its seems like its working, but breaks at very end. trying to find the real reason and fix it. thanks for your patience and help.

>  instead of the one i provide?

you mean the kernel downloaded by your script inside the chroot? i not change anything in your script. if its dl and assembling what you put in the script then its exactly must be as is. i don't know then why its tacking the modules from my own system (from outside of chroot). your scrypt can not assemble his own modules after kernel? i have no idea, sorry. 
if you will tell me how to get full log file (i provided only part from my screen from terminal and its only i have) then i can send you full log. but i dont know how to get it. can your script make a logfile right inside the folder the script run from? its will be best, i guess.

> the host libraries doesn't matter.

i have no idea. i only copy/paste you what i saw on my screen from your script run. if you need something more then tell me how please. i'll do it. thank you.

> I can reproduce that curl is missing after the remove orphans, so i will send a fix for this.

oh, thanks!!! i will try then tonight again (and will let you know later, other day). thank you again.

**Comment by eudaldgr** [comment] 2020-11-12 15:56
Well, i fixed issue with `tinyramfs`, i removed a flag some time ago, because i always use the latest stable linux kernel as this script, but it causes problems if it's not the same, as you can see by yourself. Because some enviromental variables are the same as host inside the chroot, so there's a need of especificate them. [`af0a83e`](https://github.com/eudaldgr/kiss-live/commit/af0a83ec7d701c90f8781b6483d08e18c018291f)
